# POST http://localhost:4000/app/signup
# Content-Type: application/json

# {
#     "fullName": "xyz",
#     "email": "abc153@gmail.com",
#     "phone": 999908979,
#     "restaurantName": "food chef",
#     "address": "h.no 125",
#     "password": "password"
# }

POST http://localhost:4000/app/dish
Content-Type: application/json

{
    "ItemName":"hot dog",
    "ItemImage": "img.jpg",
    "ItemDiscription": "our special dish",
    "ItemCatagory": "North Indian",
    "ItemType": "veg",
    "price": 100
}